apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon-bot-docs
  namespace: horizon-bot
spec:
  project: default
  source:
    repoURL: 'https://github.com/horizon-tempvoice/horizon-bot-docs.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: horizon-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
