apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon-bot-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horizon-bot-docs
  template:
    metadata:
      labels:
        app: horizon-bot-docs
    spec:
      containers:
      - name: horizon-bot-docs
        image: ghcr.io/horizon-tempvoice/horizon-bot-docs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
