apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: docs-redirect
  namespace: horizon-bot
spec:
  redirectRegex:
    regex: "^https?://docs\\.horizon-bot\\.me/(.*)"
    replacement: "https://horizon-bot.me/docs/${1}"
    permanent: true
